namePrefix: prod-

bases:
- ../base

commonLabels:
  environment: prod

images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newTag: "0.1"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
