namePrefix: kustomize-
configMapGenerator:
- name: guestbook-cm
  files:
  - index2.html
resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
- guestbook-ui-ing.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
