image:
  tag: "0.2"
  repository: "gcr.io/heptio-images/ks-guestbook-demo"
  pullPolicy: "IfNotPresent"
ingress:
  path: "/"
  hosts:
  - "chart-example.local"
  annotations: {}
  tls: []
  enabled: false
replicaCount: 1
tolerations: []
service:
  port: 80
  type: "ClusterIP"
containerPort: 80
resources:
  limits:
    cpu: "1"
    memory: "256Mi"
  requests:
    cpu: "1"
    memory: "256Mi"
nodeSelector: {}
affinity: {}
