apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/thirtynine96/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
  destination:
    namespace: helm-guestbook
    server: https://kubernetes.default.svc