config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/agaudreault/argocd-example-apps
      targetRevision: sync-from-demo

applications:
  - name: blue-green
    tool:
      helm:
        releaseName: blue-green
  - name: guestbook
  - name: helm-dependency
    tool:
      helm:
        releaseName: helm-dependency
  - name: helm-guestbook
    tool:
      helm:
        releaseName: helm-guestbook
  - name: helm-hooks
  - name: jsonnet-guestbook
  - name: jsonnet-guestbook-tla
  - name: kustomize-guestbook
  - name: plugin-kasane
    path: plugins/kasane
    tool:
      plugin:
        name: kasane
  - name: plugin-kustomized-helm
    path: plugins/kustomized-helm
    tool:
      plugin:
        name: kustomized-helm
  - name: plugin-nix
    path: plugins/nix
    tool:
      plugin:
        name: nix
  - name: pre-post-sync
  - name: sock-shop
  - name: sync-waves
